export interface MegaMenuCategory {
  label: string;
  filterCategory: string;
  subcategories: string[];
}

export const MEGA_MENU_CATEGORIES: MegaMenuCategory[] = [
  {
    label: "Maquiagem",
    filterCategory: "Beauty",
    subcategories: [
      "Rare Beauty",
      "Fenty Beauty",
      "Charlotte Tilbury",
      "MAC Cosmetics",
      "NARS",
      "Too Faced",
      "Urban Decay",
      "Benefit Cosmetics",
      "Tarte",
      "Huda Beauty",
      "Pat McGrath Labs",
      "Anastasia Beverly Hills",
      "NYX Professional",
      "Maybelline",
      "e.l.f. Cosmetics",
      "ColourPop",
      "Morphe",
      "Laura Mercier",
      "Bobbi Brown",
      "Hourglass",
      "Milk Makeup",
      "Tower 28",
      "Ilia Beauty",
      "Kosas",
      "Merit",
      "Saie",
      "Glossier",
      "Clinique",
      "Estée Lauder",
      "Lancôme",
      "Dior Beauty",
      "YSL Beauty",
    ],
  },
  {
    label: "Skincare",
    filterCategory: "Beauty",
    subcategories: [
      "CeraVe",
      "La Roche-Posay",
      "The Ordinary",
      "Drunk Elephant",
      "Tatcha",
      "Glow Recipe",
      "Sunday Riley",
      "Paula's Choice",
      "SK-II",
      "Estée Lauder",
      "Clinique",
      "Kiehl's",
      "Fresh",
      "Supergoop!",
      "Laneige",
      "Neutrogena",
      "Olay",
    ],
  },
  {
    label: "Perfumes",
    filterCategory: "Beauty",
    subcategories: [
      "Chanel",
      "Dior",
      "Tom Ford",
      "Yves Saint Laurent",
      "Jo Malone",
      "Marc Jacobs",
      "Viktor & Rolf",
      "Lancôme",
      "Gucci",
      "Versace",
      "Dolce & Gabbana",
      "Burberry",
      "Calvin Klein",
      "Ralph Lauren",
      "Carolina Herrera",
      "Paco Rabanne",
    ],
  },
  {
    label: "Eletrônicos",
    filterCategory: "Tech",
    subcategories: [
      "Apple",
      "Samsung",
      "Sony",
      "Bose",
      "JBL",
      "Beats",
      "Nintendo",
      "Kindle",
      "GoPro",
      "DJI",
      "Garmin",
      "Anker",
    ],
  },
  {
    label: "Roupas",
    filterCategory: "Fashion",
    subcategories: [
      "Nike",
      "Adidas",
      "Levi's",
      "Ralph Lauren",
      "Tommy Hilfiger",
      "Calvin Klein",
      "Gap",
      "H&M",
      "Zara",
      "Under Armour",
      "The North Face",
      "Patagonia",
    ],
  },
  {
    label: "Bolsas",
    filterCategory: "Lifestyle",
    subcategories: [
      "Coach",
      "Michael Kors",
      "Kate Spade",
      "Tory Burch",
      "Marc Jacobs",
      "Fossil",
      "Longchamp",
      "Guess",
      "Steve Madden",
      "Rebecca Minkoff",
      "Furla",
      "Kipling",
    ],
  },
];
