export interface MegaMenuCategory {
  label: string;
  subcategories: string[];
}

export const MEGA_MENU_CATEGORIES: MegaMenuCategory[] = [
  {
    label: "Maquiagem",
    subcategories: [
      "Fenty Beauty",
      "Charlotte Tilbury",
      "MAC Cosmetics",
      "NARS",
      "Urban Decay",
      "Too Faced",
      "Benefit Cosmetics",
      "Tarte",
      "Morphe",
      "ColourPop",
      "NYX Professional",
      "Maybelline",
      "L'Oréal Paris",
      "Revlon",
      "CoverGirl",
      "Milani",
      "e.l.f. Cosmetics",
      "Physicians Formula",
      "Wet n Wild",
      "ILIA Beauty",
      "Rare Beauty",
      "Glossier",
      "Hourglass",
      "Pat McGrath Labs",
      "Bobbi Brown",
      "Laura Mercier",
      "Dior Beauty",
      "Estée Lauder",
      "Lancôme",
      "Clinique",
      "YSL Beauty",
      "Chanel Beauty",
    ],
  },
  {
    label: "Skincare",
    subcategories: [
      "CeraVe",
      "La Roche-Posay",
      "The Ordinary",
      "Neutrogena",
      "Cetaphil",
      "Drunk Elephant",
      "Tatcha",
      "Sunday Riley",
      "Glow Recipe",
      "Paula's Choice",
      "SK-II",
      "Clinique",
      "Olay",
      "Kiehl's",
      "Murad",
      "First Aid Beauty",
      "Laneige",
    ],
  },
  {
    label: "Perfumes",
    subcategories: [
      "Chanel",
      "Dior",
      "Tom Ford",
      "YSL",
      "Lancôme",
      "Jo Malone",
      "Dolce & Gabbana",
      "Gucci",
      "Versace",
      "Prada",
      "Burberry",
      "Hermès",
      "Calvin Klein",
      "Marc Jacobs",
      "Carolina Herrera",
      "Viktor & Rolf",
    ],
  },
  {
    label: "Eletrônicos",
    subcategories: [
      "Apple",
      "Samsung",
      "Sony",
      "Bose",
      "JBL",
      "Beats by Dre",
      "Nintendo",
      "GoPro",
      "DJI",
      "Garmin",
      "Kindle",
      "Anker",
    ],
  },
  {
    label: "Roupas",
    subcategories: [
      "Nike",
      "Adidas",
      "Ralph Lauren",
      "Tommy Hilfiger",
      "Calvin Klein",
      "Levi's",
      "The North Face",
      "Patagonia",
      "Under Armour",
      "Victoria's Secret",
      "H&M",
      "Zara",
    ],
  },
  {
    label: "Bolsas",
    subcategories: [
      "Coach",
      "Michael Kors",
      "Kate Spade",
      "Tory Burch",
      "Marc Jacobs",
      "Longchamp",
      "Fossil",
      "Guess",
      "Steve Madden",
      "Kipling",
      "Samsonite",
      "Herschel",
    ],
  },
];
