ALTER TABLE public.order_reviews ADD COLUMN IF NOT EXISTS admin_reply TEXT DEFAULT NULL;
ALTER TABLE public.order_reviews ADD COLUMN IF NOT EXISTS admin_reply_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;